export const recipes = [
      {
       "id": 100,
       "name": "Martini",
       "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Bright-Field_Lighting.jpg/800px-Bright-Field_Lighting.jpg",
       "preparation": "Straight: Pour all ingredients into mixing glass with ice cubes. Stir well. Strain in chilled martini cocktail glass. Squeeze oil from lemon peel onto the drink, or garnish with olive.",
       "served": "On the rocks or Straight",
       "ingredients": "3 oz (6 parts) Gin, 1/2 oz (1 part) Dry vermouth",
       "favourite": "false",
       "tried": "false",
       "thumbsUp": 0,
       "thumbsDown": 0,
       "mainAlcohol": "Gin"
     },
     {
      "id": 101,
      "name": "Margarita",
      "imageURL": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Margarita.jpg",
      "preparation": "Rub the rim of the glass with the lime slice to make the salt stick to it. Shake the other ingredients with ice, then carefully pour into the glass (taking care not to dislodge any salt). Garnish and serve over ice.",
      "served": "On the rocks; poured over ice",
      "ingredients": "2 oz Tequila, 1 oz Lime juice, 1 oz Cointreau",
      "favourite": "false",
      "tried": "false",
      "thumbsUp": 0,
      "thumbsDown": 0,
      "mainAlcohol": "Tequila"
      },
      {
       "id": 102,
       "name": "Cosmopolitan",
       "imageURL": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Cosmopolitan_%285076906532%29.jpg",
       "preparation": "Add all ingredients into cocktail shaker filled with ice. Shake well and double strain into large cocktail glass. Garnish with lime wheel.",
       "served": "Straight up; without ice",
       "ingredients": "1/2 oz Fresh lime juice, 1 oz Cranberry juice, 1/2 oz Cointreau, 1 1/2 oz Vodka Citron",
       "favourite": "false",
       "tried": "false",
       "thumbsUp": 0,
       "thumbsDown": 0,
       "mainAlcohol": "Vodka"
     },
     {
      "id": 103,
      "name": "Mojito",
      "imageURL": "https://upload.wikimedia.org/wikipedia/commons/c/c0/MojitoReydelmojito.jpg",
      "preparation": "Mint sprigs muddled with sugar and lime juice. Rum added and topped with soda water. Garnished with sprig of mint leaves. Served with a straw.",
      "served": "On the rocks; poured over ice",
      "ingredients": "1 1/2 oz White rum, 6 leaves of Mint, Soda Water, 1 oz Fresh lime juice, 2 teaspoons Sugar",
      "favourite": "false",
      "tried": "false",
      "thumbsUp": 0,
      "thumbsDown": 0,
      "mainAlcohol": "White rum"
    },
    {
     "id": 104,
     "name": "Daiquiri",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/0/02/Daiquiri_de_fresa.jpg",
     "preparation": "Pour all ingredients into shaker with ice cubes. Shake well. Strain in chilled cocktail glass.",
     "served": "Straight up; without ice",
     "ingredients": "1 1/2 oz White rum, 1/2 oz Simple syrup, 1 oz Lime juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "White rum"
    },
    {
     "id": 105,
     "name": "Bloody Mary",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Bloody_mary.jpg",
     "preparation": "Add dashes of Worcestershire Sauce, Tabasco, salt and pepper into highball glass, then pour all ingredients into highball with ice cubes. Stir gently. Garnish with celery stalk and lemon wedge (optional).",
     "served": "On the rocks; poured over ice.",
     "ingredients": "4.5 cl (3 parts) Vodka, 9 cl (6 parts) Tomato juice, 1.5 cl (1 part) Lemon juice, 2 to 3 dashes of Worcestershire Sauce, Tabasco, Celery salt, Pepper",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Vodka"
    },
    {
     "id": 106,
     "name": "Fizz",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/15-09-26-RalfR-WLC-0032.jpg/800px-15-09-26-RalfR-WLC-0032.jpg",
     "preparation": "Shake all ingredients with ice cubes, except soda water. Pour into glass. Top with soda water",
     "served": "On the rocks; poured over ice",
     "ingredients": "4.5 cl Gin; 3 cl fresh lemon juice; 1 cl Gomme syrup; 8 cl soda water",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 107,
     "name": "Manhattan",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/A_Manhattan.jpg/800px-A_Manhattan.jpg",
     "preparation": "Stirred over ice, strained into a chilled glass, garnished, and served straight up.",
     "served": "Straight up; without ice",
     "ingredients": "Maraschino cherry (Garnish), Dash Angostura bitters, 2 oz Rye or Canadian whisky, 3/4 oz Sweet red vermouth",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Whisky"
    },
    {
     "id": 108,
     "name": "Tequila Sunrise",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/7/79/Tequila_Sunrise_garnished_with_orange_and_cherry_-_Evan_Swigart.jpg",
     "preparation": "Pour the tequila and orange juice into glass over ice. Add the grenadine, which will sink to the bottom. Do not stir. Garnish and serve.",
     "served": "On the rocks; poured over ice",
     "ingredients": "3 oz (6 parts) Orange juice, 1 1/2 oz (3 parts) Tequila, 1/2 oz (1 part) Grenadine syrup",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Tequila"
    },
    {
     "id": 109,
     "name": "Hurricane",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Hurricane_at_Pat_O%27Brien%27s.JPG/800px-Hurricane_at_Pat_O%27Brien%27s.JPG",
     "preparation": "Shake the rums, passion fruit syrup, and lemon juice with ice, then pour into the glass and serve over ice.",
     "served": "On the rocks; poured over ice",
     "ingredients": "One part dark rum; One part white rum; Half part over proofed rum; Passion fruit syrup; Lemon juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Dark rum"
    },
    {
     "id": 110,
     "name": "Long Island Iced Tea",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Adios_Motherfucker_Cocktail.jpg/600px-Adios_Motherfucker_Cocktail.jpg",
     "preparation": "Add all ingredients into highball glass filled with ice. Stir gently. Garnish with lemon spiral. Serve with straw.",
     "served": "On the rocks; poured over ice",
     "ingredients": "1.5 cl Tequila, 1.5 cl Vodka, 1.5 cl White rum, 1.5 cl Triple sec, 1.5 cl Gin, 2.5 cl Lemon juice, 3.0 cl Gomme Syrup, 1 dash of Cola",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Tequila"
    },
    {
     "id": 111,
     "name": "Clover Club Cocktail",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Clover_Club.jpg/800px-Clover_Club.jpg",
     "preparation": "Dry shake ingredients to emulsify, add ice, shake and served straight up.",
     "served": "Straight up; without ice",
     "ingredients": "1/4 oz Raspberry Syrup (or Grenadine), 1½ oz Gin, 3/4 oz Lemon Juice, 1 Egg White",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 112,
     "name": "Piña colada",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Pi%C3%B1a_colada.jpg/400px-Pi%C3%B1a_colada.jpg",
     "preparation": "Mix with crushed ice in blender until smooth. Pour into chilled glass, garnish and serve.",
     "served": "Blended with ice (frozen style)",
     "ingredients": "3 oz (3 parts) Pineapple juice, 1 oz (one part) White rum, 1 oz (one part) Coconut cream",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "White rum"
    },
    {
     "id": 113,
     "name": "Paloma",
     "imageURL": "https://i0.wp.com/drizzleanddip.com/wp-content/uploads/2012/03/MG_9171-copy.jpg?fit=700%2C1050",
     "preparation": "Stir together and serve over ice.",
     "served": "On the rocks; poured over ice",
     "ingredients": "Three parts grapefruit soda, One part tequila",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Tequila"
    },
    {
     "id": 114,
     "name": "Zombie",
     "imageURL": "https://www.gasztrotrend.hu/wp-content/uploads/2012/12/bahama-mama.jpg?x70796",
     "preparation": "Mix ingredients other than the 151 in a shaker with ice. Pour into glass and top with the high-proof rum.",
     "served": "On the rocks; poured over ice",
     "ingredients": "1 1/2 oz Puerto Rican golden rum, 1 1/2 oz Jamaican rum, 1 oz demerara 151 rum, 1/2 oz Donn's Mix (2:1 grapefruit juice:cinnamon syrup), ½ oz Velvet Falernum 3/4 oz lime juice, 1/4 oz grenadine, 2 dashes absinthe, 1 dash angostura bitters",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Rum"
    },
    {
     "id": 115,
     "name": "Aviation",
     "imageURL": "https://search.chow.com/thumbnail/800/600/www.chowstatic.com/assets/2007/04/hi_lo_cocktail_210x290.jpg",
     "preparation": " Add all ingredients into cocktail shaker filled with ice. Shake well and strain into cocktail glass. Garnish with a cherry or orange.",
     "served": "Straight up; without ice",
     "ingredients": "Crème de violette or Creme Yvette, 1/2 oz Maraschino liqueur, 1 1/2 oz Gin, 1/2 oz Lemon juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 116,
     "name": "White Russian",
     "imageURL": "https://www.wine-now.com/media/magpleasure/mpblog/upload/7/6/76e325ef8b81a272d0acc036b561201f.jpg",
     "preparation": "Pour coffee liqueur and vodka into an Old Fashioned glass filled with ice. Float fresh cream on top and stir slowly",
     "served": "On the rocks; poured over ice",
     "ingredients": "2/3 oz (2 parts) Coffee liqueur, 1 2/3 oz (5 parts) Vodka, 1 oz (3 parts) Fresh cream",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Vodka"
    },
    {
     "id": 117,
     "name": "Espresso Martini",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Bistrot_Bruno_Loubet%2C_Clerkenwell%2C_London_%284574785649%29.jpg/400px-Bistrot_Bruno_Loubet%2C_Clerkenwell%2C_London_%284574785649%29.jpg",
     "preparation": "Pour ingredients into shaker filled with ice, shake vigorously, and strain into chilled martini glass",
     "served": "Straight up; without ice",
     "ingredients": "5 cl Vodka, 1 cl Kahlua, Sugar syrup (according to individual preference of sweetness), 1 short strong Espresso",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Vodka"
    },
    {
     "id": 118,
     "name": "Cuba Libre",
     "imageURL": "https://www.brugal-rum.com/wp-content/uploads/2016/03/single-cuba-libre.png",
     "preparation": "Build all ingredients in a highball glass filled with ice. Garnish with lime wedge.",
     "served": "On the rocks; poured over ice",
     "ingredients": "4 oz Cola, 1/3 oz Fresh lime juice, 1 2/3 oz White rum",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "White rum"
    },
    {
     "id": 119,
     "name": "Bramble",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Bramble_Cocktail1.jpg/465px-Bramble_Cocktail1.jpg",
     "preparation": "Fill glass with crushed ice. Build gin, lemon juice and simple syrup over. Stir, and then pour blackberry liqueur over in a circular fashion to create marbling effect. Garnish with two blackberries and lemon slice.",
     "served": "On the rocks; poured over ice",
     "ingredients": "4 cl gin, 1.5 cl lemon juice, 1 cl simple syrup, 1.5 cl Creme de Mure(blackberry liqueur)",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 120,
     "name": "Americano",
     "imageURL": "https://cdn.diffordsguide.com/contrib/stock-images/2015/7/41/2015e59ddd7a93b2461d7165e20f90537661.jpg",
     "preparation": "Pour the Campari and vermouth over ice into glass, add a splash of soda water and garnish with half orange slice.",
     "served": "On the rocks; poured over ice",
     "ingredients": "3 cl Campari, 3 cl red vermouth, A splash of soda water",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Liqueur - Campari"
    },
    {
     "id": 121,
     "name": "Paradise",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Paradise_cocktail.jpg/600px-Paradise_cocktail.jpg",
     "preparation": "Shake together over ice. Strain into cocktail glass and serve chilled.",
     "served": "Straight up; without ice",
     "ingredients": "3.5 cl (7 parts) gin, 2 cl (4 parts) apricot brandy, 1.5 cl (3 parts) orange juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 122,
     "name": "Casino",
     "imageURL": "https://www.thedrinkblog.com/wp-content/uploads/2015/01/tdb-casino-22.jpg",
     "preparation": "Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.",
     "served": "Straight up; without ice",
     "ingredients": "4 cl gin (Old Tom), 1 cl Maraschino, 1 cl orange bitters, 1 cl fresh lemon juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Gin"
    },
    {
     "id": 123,
     "name": "Bacardi",
     "imageURL": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Cocktail_Milagrito..jpg/666px-Cocktail_Milagrito..jpg",
     "preparation": "Shake together with ice. Strain into glass and serve",
     "served": "Straight up; without ice",
     "ingredients": "4.5 cl white rum, 2 cl lime juice, 1 cl grenadine syrup",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "White rum"
    },
    {
     "id": 124,
     "name": "Screwdriver",
     "imageURL": "https://images6.alphacoders.com/553/553529.jpg",
     "preparation": "Mix in a highball glass with ice. Garnish and serve.",
     "served": "On the rocks; poured over ice",
     "ingredients": "5 cL (1 part) vodka, 10 cL (2 parts) orange juice",
     "favourite": "false",
     "tried": "false",
     "thumbsUp": 0,
     "thumbsDown": 0,
     "mainAlcohol": "Vodka"
    }
]
